### ISSUE TITLE
Remove "From" in Email Template Form

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/admin-dashboard#2]
We removed "from" in the batch set up but it is still in the email template form. Let's remove that for now.

We should keep "from" email in mind in multi-tenancy planning.

**Comment by jchartrand** [comment]
Fixed by PR https://github.com/digitalcredentials/admin-dashboard/pull/25

**Comment by alexfigtree** [comment]
Keeping open until after deployment

**Comment by alexfigtree** [comment]
Admin-dashboard now deployed, closing this ticket
