### ISSUE TITLE
Email not sending when more than two recipients in csv file

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/admin-dashboard#27]
Tec de Monterrey is reporting that email is not working if there are more than two entries n the csv file. Gathering more info. We should investigate.

Assigning to @jchartrand for investigation.

**Comment by jchartrand** [comment]
I just created a batch for which I uploaded a CSV with six rows - all emails were sent (and arrived).

I also then tried with five rows - all were properly sent, although the 'Sending' spinner did remain spinning.

**Comment by kayaelle** [comment]
Thanks for looking into this @jchartrand. I've asked for an example csv to try to replicate with that. Will ask for the templates being used too.  

I think the status doesn't update without a refresh. I noticed the same thing when revoking. Will create a separate issue.

**Comment by kayaelle** [comment]
Tec de Monterrey reported this is working. Likely related to testing with hotmail.
