### ISSUE TITLE
Move claim page from this repository into its own repository

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/admin-dashboard#34]
**Is your feature request related to a problem? Please describe.**
Can't version/tag the claim page app separately from the admin-dashboard app, even though both have their own images in DockerHub. But possibly more importantly, it is a bit confusing for anyone new to the project (or evaluating the project) to find two separate web apps in the same repo.

**Describe the solution you'd like**
Move the claim page app into its own repository.

**Describe alternatives you've considered**
Leave it where it is. The one advantage there being that with the admin-dashboard and claim-page in the same repository, they stay in sync in the sense that the two versions in the same commit should work together. If, on the other hand, they are in separate repositories, it won't necessarily be obvious which version of the claim page works with which version of the admin-dashboard. But, because we are 'versioning' in docker hub, we would still have that problem anyhow because the tagged docker images could get out of sync.  We could always keep the tag numbers the same for both, but that could mean a lot of extra images. And further, since we are using semver, the version numbers should indicate which are compatible.

Overall, especially considering that we are tying to make the repositories easy to understand for people evaluating the projects, separating them into discrete and therefore conceptually easier to understand chunks seems preferable.

**Additional context**

**Comment by alexfigtree** [comment]
Recently deployed, closing this ticket
