### ISSUE TITLE
missing null check on get-credential-links auth header crashes server

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/admin-dashboard#38]
**Describe the bug**
Missing null check on get-credential-links auth header crashes server. This is the line:

https://github.com/digitalcredentials/admin-dashboard/blob/1b26c63ad42bdd2598c79e6fabbcb8f8506f02db/src/endpoints/getCredentialLinks.ts#L18

**To Reproduce**

1. issue a GET request to get-credential-links without an auth header
2. Server crashes

**Expected behavior**

Should check that auth header exists before invoking 'startsWith' and should also move the check into the try/catch

**Comment by jchartrand** [comment]
See https://github.com/digitalcredentials/admin-dashboard/pull/39

**Comment by alexfigtree** [comment]
Recently deployed, closing this ticket
