### ISSUE TITLE
Add direct link to collection page.

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/admin-dashboard#6]
The collection page has a QR containing the LCW deeplink, which allows scanning from one's phone to thereby open the LCW.

The collection page also needs a direct link for cases where the collection page had been opened while already on one's phone.

The direct link could be something like a button that says, "Add to Learner Credential Wallet" with maybe some text somewhere that explains when to use the QR and when to use the direct link, like:

 "Are you on your phone/mobile? Click here." 

"Are you on your laptop/desktop? Scan this with your phone camera."

**Comment by jchartrand** [comment]
https://github.com/digitalcredentials/admin-dashboard/pull/24

**Comment by alexfigtree** [comment]
Tested and deployed

**Comment by alexfigtree** [comment]
Keeping open until after deployment

**Comment by alexfigtree** [comment]
Admin-dashboard-claim-page now deployed, closing this ticket
